In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [3]:
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [4]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [5]:
frame.tail(2)

state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [6]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [7]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [8]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [9]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [10]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [11]:
obj = pd.Series([4, 7, -5, 3])

In [12]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [13]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [14]:
np.random.rand(4,5)

array([[0.78749408, 0.06651089, 0.197944  , 0.08041682, 0.10955692],
       [0.40313262, 0.58931947, 0.25574714, 0.96742632, 0.59446969],
       [0.13707168, 0.99520252, 0.17665468, 0.86312109, 0.06974317],
       [0.49234104, 0.09959396, 0.22490027, 0.61003039, 0.84719281]])

In [15]:
np.random.randint(1,100)

72

In [16]:
arr = np.array(range(0,25))

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
import tensorflow as tf

In [20]:
arr_2d = np.array([[12,23,45],[45,67,89],[4,6,8]])

In [21]:
arr_2d

array([[12, 23, 45],
       [45, 67, 89],
       [ 4,  6,  8]])

In [22]:
arr_2d[0][0]

12

In [23]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr > 5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Exmaples

In [25]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [26]:
arr[arr <3]

array([1, 2])

In [27]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr * arr


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [34]:
arr / arr

<ipython-input-34-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
arr.max()

10