In [1]:
import numpy as np

In [2]:
arr = np.arange(1000)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [3]:
list = list(range(10))

In [4]:
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
r = np.random.randn(2,3)
r

array([[ 0.39455235, -1.85747841, -0.01795165],
       [ 0.38908198, -2.25619392,  0.43564504]])

In [9]:
r * r

array([[1.55671556e-01, 3.45022604e+00, 3.22261898e-04],
       [1.51384785e-01, 5.09041099e+00, 1.89786601e-01]])

In [10]:
list * list

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
arr = arr + 10

In [12]:
arr

array([  10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99,  100,  101,  102,  103,  104,  105,  106,  107,  108,
        109,  110,  111,  112,  113,  114,  115,  116,  117,  118,  119,
        120,  121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
        131,  132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
        142,  143,  144,  145,  146,  147,  148,  149,  150,  151,  152,
        153,  154,  155,  156,  157,  158,  159,  1

In [14]:
r.shape

(2, 3)

In [15]:
data1 = [1,2,3,4,5]
arr1 = np.array(data1)

In [16]:
arr1

array([1, 2, 3, 4, 5])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
iris = load_iris()
X = iris.data[:, (2, 3)] # petal length, petal width
y = (iris.target == 0).astype(np.int) # Iris Setosa?
per_clf = Perceptron()
per_clf.fit(X, y)
y_pred = per_clf.predict([[2, 0.5]])

In [22]:
y_pred

array([0])

In [23]:
per_clf

Perceptron()

In [24]:
string_ str="sdfsd"

SyntaxError: invalid syntax (<ipython-input-24-545acd93a76a>, line 1)

In [25]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [26]:
numeric_strings = np.array(['1.25', '-9.6', '42'],dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [27]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
ar[5]

5

In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [30]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr[1:6]

array([2, 3, 4])

In [32]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [34]:
import pandas as pd

In [35]:
s = pd.Series([1,2,4,np.nan,5,8,9])
s

0    1.0
1    2.0
2    4.0
3    NaN
4    5.0
5    8.0
6    9.0
dtype: float64

In [36]:
df = pd.read_csv('C:/Users/sramasam/Data/Auto.csv')


In [37]:
df

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [38]:
print(df.to_string()) 

      mpg  cylinders  displacement horsepower  weight  acceleration  year  origin                                  name
0    18.0          8         307.0        130    3504          12.0    70       1             chevrolet chevelle malibu
1    15.0          8         350.0        165    3693          11.5    70       1                     buick skylark 320
2    18.0          8         318.0        150    3436          11.0    70       1                    plymouth satellite
3    16.0          8         304.0        150    3433          12.0    70       1                         amc rebel sst
4    17.0          8         302.0        140    3449          10.5    70       1                           ford torino
5    15.0          8         429.0        198    4341          10.0    70       1                      ford galaxie 500
6    14.0          8         454.0        220    4354           9.0    70       1                      chevrolet impala
7    14.0          8         440.0      

In [39]:
arr = np.empty((8, 4))

In [40]:
arr

array([[2.12199579e-314, 1.02223711e-311, 1.02223711e-311,
        1.02223711e-311],
       [1.02228862e-311, 1.02228924e-311, 1.02228924e-311,
        1.02228924e-311],
       [1.02228924e-311, 1.02228924e-311, 1.02228924e-311,
        1.02223711e-311],
       [1.02228924e-311, 1.02228913e-311, 1.02223711e-311,
        1.02223711e-311],
       [1.02228924e-311, 1.02228924e-311, 1.02228924e-311,
        1.02228924e-311],
       [1.02228924e-311, 1.02228924e-311, 1.02228924e-311,
        1.02228913e-311],
       [1.02228913e-311, 1.02228913e-311, 1.02228913e-311,
        1.02228934e-311],
       [1.02228934e-311, 1.02228934e-311, 1.02228934e-311,
        1.02228934e-311]])

In [41]:
arr = np.arange(15).reshape((3, 5))

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])